apiVersion: v1
kind: Service
metadata:
  name: py-eagle-mqtt
  labels:
    app: py-eagle-mqtt
spec:
  selector:
    app: py-eagle-mqtt
  type: NodePort
  ports:
  - name: py-eagle
    port: 22042
    nodePort: 31242
